# Numpy

NumPy (Numerical Python) provides the ndarray (N-dimensional array) object for efficient storage and manipulation of dense, homogeneous data (all elements must be the same type).

## NumPy: ndarray Creation & dtypes

Why use ndarrays?<br>
Faster operations (C-based backend), memory efficiency, and built-in mathematical functions compared to Python lists.

 ### Creating ndarrays

In [2]:
import numpy as np
oned_arr = np.array([23, 56, 88, 10, 9, 356, 88, 90]) # 1D Array
twod_arr = np.array([[23, 56, 78, 90],[54, 88, 12, 10]]) # 2D Array
threed_arr = np.array([[345, 890, 778],[670, 500, 100],[398, 345, 900]]) #3D Array
print(f"One dimentional array \n {oned_arr} \n Two dimentional array \n {twod_arr} \n Three dimentional array \n {threed_arr} \n")



One dimentional array 
 [ 23  56  88  10   9 356  88  90] 
 Two dimentional array 
 [[23 56 78 90]
 [54 88 12 10]] 
 Three dimentional array 
 [[345 890 778]
 [670 500 100]
 [398 345 900]] 



### Built in function

In [3]:
# Array of zeros (default dtype: float64)
zeros = np.zeros((3, 3))  # 3x3 matrix of 0s

# Array of ones
ones = np.ones((2, 4))    # 2x4 matrix of 1s

# Identity matrix
identity = np.eye(3)      # 3x3 identity matrix

# Array with a range of values
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# Linearly spaced values (5 numbers between 0 and 1)
linspace_arr = np.linspace(0, 1, 5)  # [0.0, 0.25, 0.5, 0.75, 1.0]

# Random values (0 to 1)
random_arr = np.random.rand(2, 3)  # 2x3 random values

### Real life usecases 
eg. Image processing 

In [4]:
# Simulate a 3x3 pixel grayscale image (2D array)
image = np.array([[0.1, 0.2, 0.3],
                  [0.4, 0.5, 0.6],
                  [0.7, 0.8, 0.9]], dtype=np.float32)
print(image)
print(image.dtype)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
float32


## NumPy Array Shapes, Reshaping, and Transposing

### Array Shapes
Shape defines the dimensions of an array (rows, columns, depth, etc.).

In [7]:
import numpy as np
arr_shape = np.arange(100)
print(f"Original 1D array: {arr_shape} \n Applying Shape:{arr_shape.shape} \n")

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 
 Applying Shape:(100,) 



Note: Be careful when applying the 'reshape' function. Make sure the matrix has a proper length that can be evenly split.

In [ ]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9])
arr_reshape = np.reshape(arr_1d, (3, 3))
print(f"Reshape: {arr_reshape} \n Shape: {arr_reshape.shape}") 


Reshape: [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 Shape: (3, 3)


### Array Transpose  
Swaps rows and columns (e.g., row i becomes column j).

In [25]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d_big = np.array([[23, 5],
                       [45, 99],
                       [7, 8],
                       [9, 100],
                       [88, 208],
                       [300, 456]])
arr_transposed = arr_2d.T
arr_transposed_big = arr_2d_big.T
print(f"\nTransposed: {arr_transposed} \n Shape: {arr_transposed.shape}")
print(f"\nTransposed: {arr_transposed_big} \n Shape: {arr_transposed_big.shape}")



Transposed: [[1 4 7]
 [2 5 8]
 [3 6 9]] 
 Shape: (3, 3)

Transposed: [[ 23  45   7   9  88 300]
 [  5  99   8 100 208 456]] 
 Shape: (2, 6)


## NumPy Indexing & Slicing
NumPy provides powerful indexing and slicing operations to access and modify array data efficiently. 

### Basic Indexing
Access elements using integer indices.

In [ ]:
arr_index = np.array([10, 20, 30, 40, 50])
print(f"\n Output: {arr_index[0]} (first element)")    
print(f"\n Output: {arr_index[-1]} (last element)")   


 Output: 10 (first element)

 Output: 50 (last element)


### Slicing
Extract subarrays using start:stop:step.<br>
start: Inclusive (default 0).<br>
stop: Exclusive (default length).<br>
step: Interval (default 1).<br>

In [ ]:
arr_slicing = np.array([18, 89, 23, 88, 99, 63]) 
# Basic indexing - accessing a single element
print(f"Get[88] = {arr_slicing[3]}")  # Index 3 is the 4th element (0-based indexing)

# Slicing - getting a range of elements
print(f"Get[88,99,63] = {arr_slicing[3:6]}")  # From index 3 to 5 (6 is exclusive)

# Stepped slicing - getting elements with a step
print(f"Get[89] = {arr_slicing[1:3:2]}")  # From index 1 to 2 (step of 2)

# To get [88,63] we need to use stepped slicing
print(f"Get[88,63] = {arr_slicing[3:6:2]}")  # From index 3 to 5 with step of 2


Get[88] = 88
Get[88,99,63] = [88 99 63]
Get[89] = [89]
Get[88,63] = [88 63]


## NumPy Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger one, without copying data, for efficient computation.

### Core Broadcasting Rules
- Two arrays are compatible for broadcasting if for every trailing dimension (from right to left):
- Their sizes match, or
- One of them has size 1 (is stretched to match the other), or
- One of them doesn’t exist (is virtually expanded to match).

###  Scaling Data

In [6]:
import numpy as np
data = np.array([[1, 2], 
                 [3, 4], 
                 [5, 6]])

scaling_factors = np.array([10, 100])
scaled_data = data * scaling_factors
print(f"\n Data: \n{data} \n Scaling factors: {scaling_factors} \n After changes: \n{scaled_data}")




 Data: 
[[1 2]
 [3 4]
 [5 6]] 
 Scaling factors: [ 10 100] 
 After changes: 
[[ 10 200]
 [ 30 400]
 [ 50 600]]
