# Numpy

NumPy (Numerical Python) provides the ndarray (N-dimensional array) object for efficient storage and manipulation of dense, homogeneous data (all elements must be the same type).

## NumPy: ndarray Creation & dtypes

Why use ndarrays?<br>
Faster operations (C-based backend), memory efficiency, and built-in mathematical functions compared to Python lists.

 ### Creating ndarrays

In [2]:
import numpy as np
oned_arr = np.array([23, 56, 88, 10, 9, 356, 88, 90]) # 1D Array
twod_arr = np.array([[23, 56, 78, 90],[54, 88, 12, 10]]) # 2D Array
threed_arr = np.array([[345, 890, 778],[670, 500, 100],[398, 345, 900]]) #3D Array
print(f"One dimentional array \n {oned_arr} \n Two dimentional array \n {twod_arr} \n Three dimentional array \n {threed_arr} \n")



One dimentional array 
 [ 23  56  88  10   9 356  88  90] 
 Two dimentional array 
 [[23 56 78 90]
 [54 88 12 10]] 
 Three dimentional array 
 [[345 890 778]
 [670 500 100]
 [398 345 900]] 



### Built in function

In [3]:
# Array of zeros (default dtype: float64)
zeros = np.zeros((3, 3))  # 3x3 matrix of 0s

# Array of ones
ones = np.ones((2, 4))    # 2x4 matrix of 1s

# Identity matrix
identity = np.eye(3)      # 3x3 identity matrix

# Array with a range of values
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# Linearly spaced values (5 numbers between 0 and 1)
linspace_arr = np.linspace(0, 1, 5)  # [0.0, 0.25, 0.5, 0.75, 1.0]

# Random values (0 to 1)
random_arr = np.random.rand(2, 3)  # 2x3 random values

### Real life usecases 
eg. Image processing 

In [4]:
# Simulate a 3x3 pixel grayscale image (2D array)
image = np.array([[0.1, 0.2, 0.3],
                  [0.4, 0.5, 0.6],
                  [0.7, 0.8, 0.9]], dtype=np.float32)
print(image)
print(image.dtype)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
float32
