# Numpy

NumPy is the fundamental package for scientific computing in Python

## Basics

### Array Creation

#### 1. Converting a list or any iterable to an array

In [1]:
import numpy as np
array1 = np.array([1,2,3,4,5,6,7,8,9]) #array from List
array2 = np.array((6,7,8,9,10,11,12))#array from tupple
array3 = np.array(range(15,200,2))
print(array1)
print(array2)
print(array3)

[1 2 3 4 5 6 7 8 9]
[ 6  7  8  9 10 11 12]
[ 15  17  19  21  23  25  27  29  31  33  35  37  39  41  43  45  47  49
  51  53  55  57  59  61  63  65  67  69  71  73  75  77  79  81  83  85
  87  89  91  93  95  97  99 101 103 105 107 109 111 113 115 117 119 121
 123 125 127 129 131 133 135 137 139 141 143 145 147 149 151 153 155 157
 159 161 163 165 167 169 171 173 175 177 179 181 183 185 187 189 191 193
 195 197 199]


### 2) Intrinsic NumPy array creation functions

1) 1D array

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2.8162,10,0.1,dtype='float')

array([2.8162, 2.9162, 3.0162, 3.1162, 3.2162, 3.3162, 3.4162, 3.5162,
       3.6162, 3.7162, 3.8162, 3.9162, 4.0162, 4.1162, 4.2162, 4.3162,
       4.4162, 4.5162, 4.6162, 4.7162, 4.8162, 4.9162, 5.0162, 5.1162,
       5.2162, 5.3162, 5.4162, 5.5162, 5.6162, 5.7162, 5.8162, 5.9162,
       6.0162, 6.1162, 6.2162, 6.3162, 6.4162, 6.5162, 6.6162, 6.7162,
       6.8162, 6.9162, 7.0162, 7.1162, 7.2162, 7.3162, 7.4162, 7.5162,
       7.6162, 7.7162, 7.8162, 7.9162, 8.0162, 8.1162, 8.2162, 8.3162,
       8.4162, 8.5162, 8.6162, 8.7162, 8.8162, 8.9162, 9.0162, 9.1162,
       9.2162, 9.3162, 9.4162, 9.5162, 9.6162, 9.7162, 9.8162, 9.9162])

In [4]:
#linspace is used for equal number of space between given range
np.linspace(1,4,5)
#equal spaces between each element can be observerd

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

2. 2D array

In [5]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
#create a 2D matrix with a given diagonal 
np.diag([1,2,3,5,4])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 4]])

In [7]:
#create a digonal matrix with shifted diagional
np.diag([1,2,3,4],-1)
#the -1 represent the shifting positive numbers shift upwards and negetive shift downwards

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [8]:
#get the diagonals from a 2D matrix
np.diag([[1,2,3],[4,5,6],[7,8,9]])

array([1, 5, 9])

3) General ND array

In [9]:
np.zeros((2,3))#an 2X3 matrix will be formed

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Array Attributes

array.shape gives us the shape of the array  examples are given bellow

In [11]:
array = np.diag([1,2,3,5,4])
print(array)
print(f"the shape of the array is {array.shape}")

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 4]]
the shape of the array is (5, 5)


In [12]:
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array)
print(f"the shape of the array is {array.shape}")



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
the shape of the array is (4, 3)


array.ndim returns the dimentions of an array

In [15]:
print(array)
print(f"The dimentions of the array is {array.ndim}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
The dimentions of the array is 2


array.dtype returns the data type in the array

In [16]:
array.dtype

dtype('int64')

array.size returns the number of elements in the array

In [18]:
print(f"The array\n{array}\n has {array.size} elements")

The array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 has 12 elements
