<h1>Vectors</h1>

Vector is a point in a perticular co-ordinate system

<h2>Representation:</h2>

In [8]:
import numpy as np
vector = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])
print(vector)
print(vector2)

[1 2 3 4 5]
[ 6  7  8  9 10]


<h2>Distance From Origin: </h2>

In [9]:
from math import sqrt
sum_squared = 0
for i in vector:
    sum_squared+=i**2
distance_from_origin = sqrt(sum_squared)
print(f"distance from origin of vector {vector} is {distance_from_origin}")

distance from origin of vector [1 2 3 4 5] is 7.416198487095663


In [10]:
# Built in method
magnitude = np.linalg.norm(vector)
print(f"distance from origin of vector {vector} is {magnitude}")

distance from origin of vector [1 2 3 4 5] is 7.416198487095663


<h2>Elucidian Distance</h2>

Elucidian distance is the distance between two vectors

In [14]:
vector = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])
if len(vector) == len(vector2):
  sum_sqrd=0
  for i in range(len(vector)):
    sum_sqrd+=(vector2[i]-vector[i])**2
  final_res = sqrt(sum_sqrd)
  print(f"distance between 2 vectirs {vector} and {vector2} is {final_res}")
else:
  print("vectors are not of same legnth")

distance between 2 vectirs [1 2 3 4 5] and [ 6  7  8  9 10] is 11.180339887498949


##Dot Product





In [21]:
if len(vector) == len(vector2):
  sum=0
  for i in range(len(vector)):
    sum+=(vector2[i]*vector[i])
  print(sum)

130


##scaller Addition and Subraction

In [23]:
print(vector + 100)
print(vector2 - 100)

[101 102 103 104 105]
[-94 -93 -92 -91 -90]
